<?php
/*
Plugin Name: Apprex LMS Wordpress Integration
Plugin URI: https://www.apprex.de/plugins/wordpress
Description: Integriere deine Onlinekurse aus apprex direkt in WordPress
Author: Andreas Pabst von apprex.de
Author URI: https://www.andreaspabst.com
Version: 1.0.0
*/

// Direkten Aufruf dieser Datei verhindern
if (!defined('WPINC')) {
     die;
}
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ApprexEinstellungen
{
     private $apprex_einstellungen_options;

     public function __construct()
     {
          add_action('admin_menu', array($this, 'apprex_einstellungen_add_plugin_page'));
          add_action('admin_init', array($this, 'apprex_einstellungen_page_init'));
     }

     public function apprex_einstellungen_add_plugin_page()
     {
          add_options_page(
               'Apprex Einstellungen', // page_title
               '🚀 Apprex', // menu_title
               'manage_options', // capability
               'apprex-einstellungen', // menu_slug
               array($this, 'apprex_einstellungen_create_admin_page') // function
          );
     }

     public function apprex_einstellungen_create_admin_page()
     {
          $this->apprex_einstellungen_options = get_option('apprex_einstellungen_option_name'); ?>

          <div class="wrap">
               <h2>Apprex Einstellungen</h2>
               <p>Füge deine apprex Akademie mit wenigen Schritten zu deiner WordPress Instanz hinzu oder nutze individuell unsere Shortcodes.</p>
               <?php settings_errors(); ?>

               <form method="post" action="options.php">
                    <?php
                    settings_fields('apprex_einstellungen_option_group');
                    do_settings_sections('apprex-einstellungen-admin');
                    submit_button();
                    ?>
               </form>
          </div>
<?php }

     public function apprex_einstellungen_page_init()
     {
          register_setting(
               'apprex_einstellungen_option_group', // option_group
               'apprex_einstellungen_option_name', // option_name
               array($this, 'apprex_einstellungen_sanitize') // sanitize_callback
          );

          add_settings_section(
               'apprex_einstellungen_setting_section', // id
               'Settings', // title
               array($this, 'apprex_einstellungen_section_info'), // callback
               'apprex-einstellungen-admin' // page
          );

          add_settings_field(
               'url_deiner_akademie_0', // id
               'URL deiner Akademie:', // title
               array($this, 'url_deiner_akademie_0_callback'), // callback
               'apprex-einstellungen-admin', // page
               'apprex_einstellungen_setting_section' // section
          );

          add_settings_field(
               'apprex_api_key_1', // id
               'apprex API Key', // title
               array($this, 'apprex_api_key_1_callback'), // callback
               'apprex-einstellungen-admin', // page
               'apprex_einstellungen_setting_section' // section
          );

          add_settings_field(
               'maximale_kursanzahl_2', // id
               'Maximale Kursanzahl', // title
               array($this, 'maximale_kursanzahl_2_callback'), // callback
               'apprex-einstellungen-admin', // page
               'apprex_einstellungen_setting_section' // section
          );
     }

     public function apprex_einstellungen_sanitize($input)
     {
          $sanitary_values = array();
          if (isset($input['url_deiner_akademie_0'])) {
               $sanitary_values['url_deiner_akademie_0'] = sanitize_text_field($input['url_deiner_akademie_0']);
          }

          if (isset($input['apprex_api_key_1'])) {
               $sanitary_values['apprex_api_key_1'] = sanitize_text_field($input['apprex_api_key_1']);
          }

          if (isset($input['maximale_kursanzahl_2'])) {
               $sanitary_values['maximale_kursanzahl_2'] = sanitize_text_field($input['maximale_kursanzahl_2']);
          }

          return $sanitary_values;
     }

     public function apprex_einstellungen_section_info()
     {
     }

     public function url_deiner_akademie_0_callback()
     {
          printf(
               '<input class="regular-text" type="text" name="apprex_einstellungen_option_name[url_deiner_akademie_0]" id="url_deiner_akademie_0" value="%s">',
               isset($this->apprex_einstellungen_options['url_deiner_akademie_0']) ? esc_attr($this->apprex_einstellungen_options['url_deiner_akademie_0']) : ''
          );
     }

     public function apprex_api_key_1_callback()
     {
          printf(
               '<input class="regular-text" type="text" name="apprex_einstellungen_option_name[apprex_api_key_1]" id="apprex_api_key_1" value="%s">',
               isset($this->apprex_einstellungen_options['apprex_api_key_1']) ? esc_attr($this->apprex_einstellungen_options['apprex_api_key_1']) : ''
          );
     }

     public function maximale_kursanzahl_2_callback()
     {
          printf(
               '<input class="regular-text" type="text" name="apprex_einstellungen_option_name[maximale_kursanzahl_2]" id="maximale_kursanzahl_2" value="%s">',
               isset($this->apprex_einstellungen_options['maximale_kursanzahl_2']) ? esc_attr($this->apprex_einstellungen_options['maximale_kursanzahl_2']) : ''
          );
     }
}
if (is_admin())
     $apprex_einstellungen = new ApprexEinstellungen();

/* 
 * Retrieve this value with:
 * $apprex_einstellungen_options = get_option( 'apprex_einstellungen_option_name' ); // Array of All Options
 * $url_deiner_akademie_0 = $apprex_einstellungen_options['url_deiner_akademie_0']; // URL deiner Akademie:
 * $apprex_api_key_1 = $apprex_einstellungen_options['apprex_api_key_1']; // apprex API Key
 * $maximale_kursanzahl_2 = $apprex_einstellungen_options['maximale_kursanzahl_2']; // Maximale Kursanzahl
 */


// Funktion zum Laden der CSS Datei
function apprex_css()
{
     wp_enqueue_style('apprex-style', plugin_dir_url(__FILE__) . 'apprex.css');
}

// Die Funtion ap_css() zur Action wp_enqueue_scripts hinzufügen
// Dieser Action-Hook wird zum Ladsen sowohl für JavaScript- als auch für CSS-Dateien verwendet
// Es gibt keinen eigenen Hook für CSS
add_action('wp_enqueue_scripts', 'apprex_css');



// function that runs when shortcode is called
function apprex_shortcode($atts, $content, $tag = '')
{
     $html = "";

     // Things that you want to do. 
     $settings = get_option('apprex_einstellungen_option_name');
     if (isset($settings["url_deiner_akademie_0"]) && !empty($settings["url_deiner_akademie_0"])) {
          $url = $settings["url_deiner_akademie_0"];
          $atts = array_change_key_case( (array) $atts, CASE_LOWER );#
          // var_dump($atts);
          // override default attributes with user attributes
          $apprex_atts = shortcode_atts(
               array(
                    'category_id' => null,
                    'filter' => array(),
               ), $atts, $tag
          );
          // var_dump($apprex_atts["filter"]);
          // exit;
          $WP_Http_Curl = new WP_Http_Curl();
          try {
               $reqUrl = $url. "api/courses/list?";
               if ($apprex_atts["filter_title"] != null) { $reqUrl .= "&filter[title]=".$apprex_atts["filter_title"]; }
               $response = $WP_Http_Curl->request($reqUrl , ['headers' => ['accept' => 'application/json']]);
               if (is_array($response) && isset($response["body"])) {
                    $courses = json_decode($response["body"]);
                    $html .= "<div class=\"apprex-row\">\n";
                    foreach ($courses as $course) {
                         $html .= "<div class=\"apprex-col-3\">\n";
                         $html .= "<img src=\"" . $course->image_url . "\">\n";
                         $html .= "<strong>" . $course->title . "</strong>\n";
                         $html .= "<p>" . $course->content_excerpt . "</p>\n";
                         $html .= "<strong>" . $course->currentPrice . " € </strong> <br>\n";
                         $html .= "<i>Der Kurs beinhaltet " . $course->modules_count . " Module </i>\n";
                         $html .= "<a href=\"".$url."/courses/".$course->slug."/?utm_source=app_wpp\" target=\"_blank\" class=\"apprex-button\">Mehr erfahren...</a>\n";
                         $html .= "</div>\n";
                    }
                    $html .= "</div>";
               } else if (isset($response->errors)) {
                    $html .= "Beim Abruf unserer Kurse (".$url.") ist ein Fehler unterlaufen. ";
               }
          } catch (\WP_Error $e) {
               // there seems to be something wrong
          } catch (\Exception $e) {
               // also..
          }
     }

     // Output needs to be return
     return $html;
}
// register shortcode
add_shortcode('apprex', 'apprex_shortcode');
